### ISSUE TITLE
DRAM-setup.py prepare_databases --skip_uniref produces error

### ISSUE THREAD

**Issue by ipetrushin** [WrightonLabCSU/DRAM#171] opened 2022-04-15 03:42 UTC
I run `DRAM-setup.py prepare_databases --skip_uniref --output_dir DRAM_data`, trying to skip UNIRef DB step, but it fails twice.
Maybe it's related to previous CONFIG file (envs/dram/lib/python3.10/site-packages/mag_annotator/CONFIG)? 
```/home/ipetrushin/miniconda3/envs/dram/lib/python3.10/site-packages/mag_annotator/database_handler.py:51: UserWarning: Database does not exist at path /beegfs/data/hpcws/ws1/ipetrushin-dram/DRAM_data/description_db.sqlite
  warnings.warn('Database does not exist at path %s' % self.description_loc)
2022-04-14 20:58:23.194637: Database preparation started
Downloading dbCAN family activities from : https://bcb.unl.edu/dbCAN2/download/Databases/V10/CAZyDB.07292021.fam-activities.txt
Downloading dbCAN from: http://bcb.unl.edu/dbCAN2/download/dbCAN-HMMdb-V10.txt
0:00:20.342400: dbCAN database processed
3:22:08.876996: PFAM database processed
3:22:47.547111: RefSeq viral database processed
3:25:15.623411: MEROPS database processed
3:27:41.155508: VOGdb database processed
3:34:53.516893: KOfam database processed
3:34:57.553807: KOfam ko list processed
3:34:57.553817: PFAM hmm dat processed
3:34:57.553819: dbCAN fam activities processed
3:34:57.995963: VOGdb annotations processed
3:35:01.932675: DRAM databases and forms downloaded
3:35:01.977743: Files moved to final destination
Traceback (most recent call last):
  File "/home/ipetrushin/miniconda3/envs/dram/bin/DRAM-setup.py", line 158, in <module>
    args.func(**args_dict)
  File "/home/ipetrushin/miniconda3/envs/dram/lib/python3.10/site-packages/mag_annotator/database_processing.py", line 374, in prepare_databases
    db_handler.populate_description_db(output_dbs['description_db_loc'], update_config=False)
  File "/home/ipetrushin/miniconda3/envs/dram/lib/python3.10/site-packages/mag_annotator/database_handler.py", line 235, in populate_description_db
    self.add_descriptions_to_database(self.make_header_dict_from_mmseqs_db(self.db_locs['uniref']) ,
  File "/home/ipetrushin/miniconda3/envs/dram/lib/python3.10/site-packages/mag_annotator/database_handler.py", line 155, in make_header_d
ict_from_mmseqs_db
    mmseqs_headers_handle = open('%s_h' % mmseqs_db, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/beegfs/data/hpcws/ws1/ipetrushin-dram/DRAM_data/uniref90.20220403.mmsdb_h'
```

**Comment by rmFlynn** [comment] 2022-04-18 16:45
This is a bug and I think I know the cause. I will plan to fix it in the next version, but it is possible that re-importing the default config file from GitHub before upgrading may fix the error. I can give more instructions, as even simple changes to dram can take a long time to test and release at this time.

**Comment by rmFlynn** [comment] 2022-10-14 14:57
I am closing this for now as you did not need more instructions, I assume you solved this problem

**Closed by rmFlynn** 2022-10-14 14:57 UTC
