### ISSUE TITLE
TypeError: annotate_bins_cmd() got an unexpected keyword argument 'prodigal_mode'

### ISSUE THREAD

**Issue by bioshaolin** [WrightonLabCSU/DRAM#21] opened 2020-07-27 19:36 UTC
Hi Michael. Our group is excited to begin using your tool. I'm running into an error when DRAM.py is compiling arguments.

`Traceback (most recent call last):
  File "DRAM/scripts/DRAM.py", line 126, in <module>
    args.func(**args_dict)
TypeError: annotate_bins_cmd() got an unexpected keyword argument 'prodigal_mode'
`

_Things I can verify_:
1. DRAM is installed
2. DRAM-setup.py set_db_locations worked properly as "print_config" confirms db locations
3. the dram environment has all dependencies.
4. running with adequate memory

_Things I've attempted_:
1. re-install dependencies
2. re-cloned repository (checking for new commits)
3. manually set "--prodigal_mode" options to see if error drops

Any help here would be greatly appreciated.

Best,

Eric Getz
egetz@usc.edu

**Comment by shafferm** [comment] 2020-07-30 23:36
Hello Eric,

I'm having trouble reproducing this on my end. What is the most recent commit that you see when you look at `git log` in the DRAM directory? Also what is the full command you are using to run `DRAM.py annotate`.

Mike

**Comment by bioshaolin** [comment] 2020-08-06 18:27
**Most recent commit:** 07.29.20, 14:26

**Full command without --prodigal_mode**
conda activate dram
python DRAM/scripts/DRAM.py annotate -i '/nt_dir/*.fna' -o /dram_all_mark_test

**Full command with --prodigal_mode**
conda actiavte dram
python DRAM/scripts/DRAM.py annotate -i '/nt_dir/*.fna' -o /dram_all_mark_test --prodigal_mode train

_NOTE:_ Both command attempts are being run through slurm script

**Comment by shafferm** [comment] 2021-02-15 23:32
Hi @bioshaolin,

I'm going through my backlog of issues and realized I never followed up with you. Sorry about that! I think his issue should have been fixed in a release. Otherwise this may have been caused by calling the DRAM.py script directly instead of the one installed during the conda installation.

Mike

**Comment by rmFlynn** [comment] 2022-06-21 20:06
This issue looks to no longer be relevant

**Closed by rmFlynn** 2022-06-21 20:06 UTC
